//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShopping.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Quantity { get; set; }
        public Nullable<double> Buy_Price { get; set; }
        public Nullable<double> Sell_Price { get; set; }
        public string Pic { get; set; }
        [NotMapped]
        public HttpPostedFileBase Pro_Pic { get; set; }

        public Nullable<int> Cate_id { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
